### ISSUE TITLE
php exec 

### ISSUE THREAD

**Issue by stevegroom** [torvitas/docker-php-fpm#5]
I am using php7-fpm as part of migrating a symphony development environment from zend-server. Performance is not there yet, but I am hopeful. I am checking for differences between my old dev environment and this one. I saw that the php exec command is not quite working though.  

Some commands work, and others fail silently. 

i.e. 
`which git` 
returns 
`/usr/bin/git`

however 
`git branch`
returns nothing.

function exec is enabled in php.ini, I suspect something is going on with the user:
`www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin`
perhaps the nologin shell is the cause. 

Not really sure if it's an issue or my (mis-)understanding. I realise that it is not best practice to use exec in general and I will look for better solutions in the future, but in the meantime I'd like to get this to work.

 regards
Steve

**Comment by torvitas** [comment]
Are you still having this problem?
